before_install:
  - "sudo add-apt-repository ppa:koffeinflummi/armake -y"
  - "sudo apt-get update -q"
  - "sudo apt-get install armake -y"
  - "sudo apt-get install sshpass -y"
script:
  - "bash -x ./build.sh"
